# Generated by Django 5.2.3 on 2025-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
